### ISSUE TITLE
How to add new field ?

### ISSUE THREAD

**Issue by lokeshjoshicis** [z3ymd/mautic#1]
Currently in this plugin have default fields name,description and i want to add some more fields. Can you please guide me how to add new field in form.

Thanks.

**Comment by z3ymd** [comment]
Hi @lokeshjoshicis thanks for your question.

Please read this [documentation](https://symfony.com/doc/2.8/form/dynamic_form_modification.html) and [this](https://developer.mautic.org/#forms)

Form class for editing `/Form/Type/BarType.php`

**Comment by lokeshjoshicis** [comment]
Hello  @thesaint326 
I have checked given documentation but unable to add new field in existing form.
When we use  $builder->add its overriding existing fields and showing new fields only.

I have checked with  EventListener as well but its not working.

Can you please provide me step by step process for adding new fields and easily store in DB.

Thanks
